seeds:
  - name: lkp_divisions
    config:
      schema: "{{ env_var('DBT_LKPSCHEMA_NAME','LOOKUP_DEV') }}"
  - name: lkp_categories
    config:
      schema: "{{ env_var('DBT_LKPSCHEMA_NAME','LOOKUP_DEV') }}"
  - name: lkp_shipments
    config:
      schema: "{{ env_var('DBT_LKPSCHEMA_NAME','LOOKUP_DEV') }}"
